language: ruby
sudo: false

rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - 2.5.0
  - jruby
  - ruby-head
before_install:
  - gem update --system
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true
