Rlanguage: ruby
sudo: false

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - truffleruby
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

install:
  - gem install bundler
  - bundle install
