Rlanguage: ruby

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - truffleruby
  - ruby-head

matrix:
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
  fast_finish: true

install:
  - gem install bundler
  - bundle install
