language: ruby
sudo: false

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-head
  - ruby-head
before_install:
  - gem update --system
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
