require 'rexml/document'
require 'rexml/xpath'

module RandomSources

  # The HotBits class uses the http service provided by http://www.fourmilab.ch/hotbits/
  #
  # The service offers genuine random numbers generated by timing successive pairs of radioactive decays detected by a Geiger-Muller tube.
  #
  # The service assigns a quota of available random bits per IP.
  #
  # Use the service properly and check the website if you need more details about the terms of usage.
  class HotBits
    attr_reader :website

    def initialize
      @website = "http://www.fourmilab.ch/hotbits/"
    end

    # Short info about the online source.
    def info
      "HotBits is an Internet resource that brings genuine random numbers, generated by a process fundamentally governed by the inherent uncertainty in the quantum mechanical laws of nature:
       HotBits are generated by timing successive pairs of radioactive decays detected by a Geiger-Muller tube interfaced to a computer. The website is mantained by John Walker."
    end

    # Random bytes generator.
    #
    # It returns an Array of integers with values between 0 and 255
    #
    # It receives the number of random bytes to generate (max 2048, default 10) 
    def bytes(num=10)
      num = [[2048, num.to_i].min , 0].max
      numbers = []

      response = REXML::Document.new( open("https://www.fourmilab.ch/cgi-bin/Hotbits?fmt=xml&nbytes=#{num}"))
      status = REXML::XPath.first( response, "//status")
      case status.attributes['result'].to_i 
      when 200
       data = REXML::XPath.first( response, "//random-data" ).text.split
       data.each{|byte| numbers << byte.hex}
      when 503
       raise StandardError.new "#{status.text}"
      end

      numbers
    end
  end  

end