require 'rexml/document'
require 'rexml/xpath'

module RandomSources

  class HotBits
    attr_reader :website

    def initialize
      @website = "http://www.fourmilab.ch/hotbits/"
    end

    def info
      "HotBits is an Internet resource that brings genuine random numbers, generated by a process fundamentally governed by the inherent uncertainty in the quantum mechanical laws of nature:
       HotBits are generated by timing successive pairs of radioactive decays detected by a Geiger-Muller tube interfaced to a computer. The website is mantained by John Walker."
    end

    def bytes(num=10)
      num = [[2048, num.to_i].min , 0].max
      numbers = []

      response = REXML::Document.new( open("https://www.fourmilab.ch/cgi-bin/Hotbits?fmt=xml&nbytes=#{num}"))
      status = REXML::XPath.first( response, "//status")
      case status.attributes['result'].to_i 
      when 200
       data = REXML::XPath.first( response, "//random-data" ).text.split
       data.each{|byte| numbers << byte.hex}
      when 503
       raise StandardError.new "#{status.text}"
      end

      numbers
    end
  end  

end